version: '3.4'
services:
  doowaste-app:
    image: salmaba/doowaste:${TAG_VERSION:-latest}
    ports:
      - "8080:8080"
    depends_on:
      - doowastedb
    networks:
      - doowaste-network

  doowastedb:
    image: "mysql:latest"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=doowaste
    ports:
      - "3306:3306"
    networks:
      - doowaste-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  doowaste-network:
    driver: bridge
volumes:
  mysql-data: